# Generated by Django 3.2.6 on 2021-08-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20210819_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=2, upload_to=None),
            preserve_default=False,
        ),
    ]
